/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wildcodeschool.sea8.exercise.junit_jupiter_getting_started;

public class App {
    public String concatenate(String one, String two){
        return one + two;
    }

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
