/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wildcodeschool.sea8.exercise.junit_jupiter_getting_started;

public class Calculator {
    public int add(int fred, int george){
        return fred + george;
    }

    public int substract(int fred, int george){
        return fred - george;
    }

        
}

