/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wildcodeschool.sea8.exercise.junit_jupiter_getting_started;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testConcatenate() {
        App classUnderTest = new App();
        
        String result = classUnderTest.concatenate("one", "two");
        
        assertEquals("onetwo", result);
    }
}
